/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_new_demo1_native_demo_MemTest */

#ifndef _Included_com_zw_new_demo1_native_demo_MemTest
#define _Included_com_zw_new_demo1_native_demo_MemTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_new_demo1_native_demo_MemTest
 * Method:    native_test1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zw_new_1demo1_native_1demo_MemTest_native_1test1
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
