/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_new_demo1_util_MMap */

#ifndef _Included_com_zw_new_demo1_util_MMap
#define _Included_com_zw_new_demo1_util_MMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_new_demo1_util_MMap
 * Method:    native_read
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zw_new_1demo1_util_MMap_native_1read
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zw_new_demo1_util_MMap
 * Method:    native_write
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_zw_new_1demo1_util_MMap_native_1write
        (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
