/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_mylibrary_Test */

#ifndef _Included_com_zw_mylibrary_Test
#define _Included_com_zw_mylibrary_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_mylibrary_Test
 * Method:    test1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zw_mylibrary_Test_test1
(JNIEnv *, jclass);

/*
 * Class:     com_zw_mylibrary_Test
 * Method:    test2
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zw_mylibrary_Test_test2
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zw_mylibrary_Test
 * Method:    test3
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_zw_mylibrary_Test_test3
(JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_zw_mylibrary_Test
 * Method:    test4
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_zw_mylibrary_Test_test4
(JNIEnv *, jclass, jintArray);

/*
 * Class:     com_zw_mylibrary_Test
 * Method:    test5
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_zw_mylibrary_Test_test5
(JNIEnv *, jclass, jchar);

/*
 * Class:     com_zw_mylibrary_Test
 * Method:    test6
 * Signature: ([CI)V
 */
JNIEXPORT void JNICALL Java_com_zw_mylibrary_Test_test6
(JNIEnv *, jclass, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
